import os

APP_NAME = "unison-io-braille"
ORCH_HOST = os.getenv("UNISON_ORCH_HOST", "orchestrator")
ORCH_PORT = os.getenv("UNISON_ORCH_PORT", "8080")
DEFAULT_PERSON_ID = os.getenv("UNISON_DEFAULT_PERSON_ID", "local-user")
ORCH_AUTH_TOKEN = os.getenv("UNISON_ORCH_AUTH_TOKEN")
REQUIRED_SCOPE_INPUT = os.getenv("UNISON_BRAILLE_SCOPE_INPUT", "braille.input.read")
REQUIRED_SCOPE_DEVICES = os.getenv("UNISON_BRAILLE_SCOPE_DEVICE", "braille.device.pair")
REQUIRED_SCOPE_OUTPUT = os.getenv("UNISON_BRAILLE_SCOPE_OUTPUT", "braille.output.write")
AUTH_JWKS_URL = os.getenv("UNISON_AUTH_JWKS_URL")
AUTH_INTROSPECT_URL = os.getenv("UNISON_AUTH_INTROSPECT_URL")
AUTH_CLIENT_ID = os.getenv("UNISON_AUTH_CLIENT_ID")
AUTH_CLIENT_SECRET = os.getenv("UNISON_AUTH_CLIENT_SECRET")
